# Generated by Django 5.2.7 on 2025-12-11 13:50

import django.db.models.deletion
import martor.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contest', '0001_initial'),
        ('lessons', '0001_initial'),
        ('users', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, unique=True)),
                ('slug', models.SlugField(max_length=500, unique=True)),
            ],
            options={
                'verbose_name': 'Kategoriya',
                'verbose_name_plural': 'Kategoriyalar',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=250, unique=True)),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
            ],
            options={
                'verbose_name': 'Dasturlash tili',
                'verbose_name_plural': 'Dasturlash tillari',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Teg',
                'verbose_name_plural': 'Teglar',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('problem_type', models.CharField(choices=[('darslik', 'darslik'), ('test', 'test'), ('probelm', 'probelm')], default=False, max_length=50)),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=250, unique=True)),
                ('description', martor.models.MartorField()),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('constraints', models.TextField(default='\n        <ul>\n            <li><code>2 ≤ nums.length ≤ 10<sup>4</sup></code></li>\n        </ul>\n        ', help_text='HTML formatida cheklovlar')),
                ('difficulty', models.PositiveIntegerField(choices=[(1, 'Oson'), (2, 'O‘rtacha'), (3, 'Qiyin')], default=1)),
                ('points', models.PositiveIntegerField(blank=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='problems', to='problems.category')),
                ('contest', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='problems', to='contest.contest')),
                ('language', models.ManyToManyField(blank=True, related_name='problems', to='problems.language')),
                ('lesson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='problems', to='lessons.lesson')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.baseuser')),
                ('tags', models.ManyToManyField(blank=True, related_name='problems', to='problems.tags')),
            ],
            options={
                'verbose_name': 'Masala',
                'verbose_name_plural': 'Masalalar',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Hint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hints', to='problems.problem')),
            ],
        ),
        migrations.CreateModel(
            name='Examples',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('input_txt', models.TextField(help_text="Kirish ma'lumotlari, masalan: '[2,7,11,15]\\n9'")),
                ('output_txt', models.TextField(help_text="Chiqish ma'lumotlari, masalan: '[0,1]'")),
                ('explanation', models.TextField(help_text='Tushuntirish matni')),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='examples', to='problems.problem')),
            ],
            options={
                'verbose_name': 'Misol',
                'verbose_name_plural': 'Misollar',
            },
        ),
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='challenges', to='problems.problem')),
            ],
        ),
        migrations.CreateModel(
            name='TestCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('input_txt', models.CharField(help_text='Test Input', max_length=250)),
                ('output_txt', models.CharField(help_text='Chiqish Output', max_length=250)),
                ('is_correct', models.BooleanField(default=True)),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_problem', to='problems.problem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.baseuser')),
            ],
            options={
                'verbose_name': 'Test case',
                'verbose_name_plural': 'Test caselar',
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('description', models.TextField(blank=True)),
                ('original_file', models.FileField(help_text='Asl video fayl', upload_to='videos/originals/')),
                ('status', models.CharField(choices=[('pending', 'Kutilmoqda'), ('uploading', 'Yuklanmoqda'), ('processing', 'Qayta ishlanmoqda'), ('completed', 'Tayyor'), ('failed', 'Xatolik')], default='pending', max_length=20)),
                ('duration', models.PositiveIntegerField(default=0, help_text='Soniyalarda')),
                ('views_count', models.PositiveIntegerField(default=0)),
                ('likes_count', models.PositiveIntegerField(default=0)),
                ('dislikes_count', models.PositiveIntegerField(default=0)),
                ('width', models.IntegerField(blank=True, null=True)),
                ('height', models.IntegerField(blank=True, null=True)),
                ('fps', models.FloatField(blank=True, null=True)),
                ('bitrate', models.IntegerField(blank=True, null=True)),
                ('codec', models.CharField(blank=True, max_length=50)),
                ('file_size', models.BigIntegerField(blank=True, help_text='Baytlarda', null=True)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='videos/thumbnails/')),
                ('hls_playlist', models.CharField(blank=True, help_text='master.m3u8 fayl manzili', max_length=500)),
                ('processing_progress', models.IntegerField(default=0)),
                ('processing_error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('problem', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='videos', to='problems.problem')),
            ],
            options={
                'verbose_name': 'Video',
                'verbose_name_plural': 'Videolar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VideoQuality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quality', models.CharField(help_text='Masalan: 360p, 720p, 1080p', max_length=20)),
                ('width', models.IntegerField()),
                ('height', models.IntegerField()),
                ('file_path', models.CharField(max_length=500)),
                ('file_size', models.BigIntegerField(default=0, help_text='Baytlarda')),
                ('is_ready', models.BooleanField(default=False)),
                ('bitrate', models.CharField(default='0k', help_text='Masalan: 800k, 2800k', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qualities', to='problems.video')),
            ],
            options={
                'verbose_name': 'Video Sifati',
                'verbose_name_plural': 'Video Sifatlari',
                'ordering': ['height'],
            },
        ),
        migrations.CreateModel(
            name='Function',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('function', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.baseuser')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='problems.language')),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='functions', to='problems.problem')),
            ],
            options={
                'verbose_name': 'Funksiya shabloni',
                'verbose_name_plural': 'Funksiya shablonlari',
                'unique_together': {('problem', 'language')},
            },
        ),
        migrations.CreateModel(
            name='ExecutionTestCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.TextField()),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='execution_language', to='problems.language')),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='execution_problem', to='problems.problem')),
            ],
            options={
                'verbose_name': 'Ishga tushirish testi',
                'verbose_name_plural': 'Ishga tushirish testlari',
                'unique_together': {('problem', 'language')},
            },
        ),
        migrations.AddIndex(
            model_name='problem',
            index=models.Index(fields=['is_active', 'difficulty'], name='problems_pr_is_acti_bcc8b6_idx'),
        ),
        migrations.AddIndex(
            model_name='problem',
            index=models.Index(fields=['slug'], name='problems_pr_slug_19f4ac_idx'),
        ),
        migrations.AddIndex(
            model_name='testcase',
            index=models.Index(fields=['problem'], name='problems_te_problem_71dd6a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='videoquality',
            unique_together={('video', 'quality')},
        ),
    ]
