# Generated by Django 5.2.7 on 2025-12-14 03:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='executiontestcase',
            old_name='code',
            new_name='bootom_code',
        ),
        migrations.RemoveField(
            model_name='function',
            name='user',
        ),
        migrations.RemoveField(
            model_name='testcase',
            name='user',
        ),
        migrations.AddField(
            model_name='executiontestcase',
            name='top_code',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='problem',
            name='points',
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='problem',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='video',
            name='slug',
            field=models.SlugField(blank=True, max_length=300, unique=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='title',
            field=models.CharField(default='Untitled Video', max_length=255),
        ),
    ]
