# Generated by Django 5.2.7 on 2025-12-14 03:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='user',
        ),
    ]
