# Generated by Django 5.2.7 on 2025-12-11 13:50

import django.db.models.deletion
import martor.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Nomi')),
                ('slug', models.SlugField(max_length=200, verbose_name='slug')),
                ('contest_type', models.CharField(choices=[('yopiq', 'Yopiq'), ('ochiq', 'Ochiq')], max_length=20, verbose_name='Turi')),
                ('contest_key', models.PositiveIntegerField(blank=True, help_text='Tanlov Kaliti', null=True, verbose_name='Kalit')),
                ('start_time', models.DateTimeField(verbose_name='Boshlanish vaqti')),
                ('duration', models.PositiveIntegerField(help_text='Daqiqalarda', verbose_name='Davomiyligi')),
                ('description', martor.models.MartorField(blank=True, null=True, verbose_name='Tavsif')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan')),
            ],
            options={
                'verbose_name': 'Contest',
                'verbose_name_plural': 'Contestlar',
                'ordering': ['-start_time'],
            },
        ),
        migrations.CreateModel(
            name='UserContestStats',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='contest_stats', serialize=False, to='users.baseuser')),
                ('total_contests', models.PositiveIntegerField(default=0)),
                ('best_rank', models.PositiveIntegerField(blank=True, null=True)),
                ('average_rank', models.FloatField(blank=True, null=True)),
                ('total_points', models.PositiveIntegerField(default=0)),
                ('last_contest', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contest.contest')),
            ],
            options={
                'verbose_name': 'Contest Statistika',
                'verbose_name_plural': 'Contest Statistikalar',
            },
        ),
        migrations.CreateModel(
            name='ContestRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registered_at', models.DateTimeField(auto_now_add=True, verbose_name="Ro'yxatdan o'tgan")),
                ('is_participated', models.BooleanField(default=False, verbose_name='Ishtirok etdi')),
                ('contest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='contest.contest')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contest_registrations', to='users.baseuser')),
            ],
            options={
                'verbose_name': "Contest Ro'yxati",
                'verbose_name_plural': "Contest Ro'yxatlari",
                'unique_together': {('user', 'contest')},
            },
        ),
    ]
